[package]
name = "meshtext"
version = "0.1.0"
edition = "2021"
description = "Generate vertex-vertex meshes from text."
readme = "README.md"
repository = "https://github.com/FrankenApps/meshtext"
documentation = "https://docs.rs/meshtext"
license = "MIT OR Apache-2.0"
keywords = ["graphics", "gamedev", "delauny", "render", "triangulation"]
categories = ["graphics", "game-development", "rendering"]

[dependencies]
cdt = "0.1.0"
glam = "0.20.2"
ttf-parser = "0.15.0"

[dev-dependencies]
gltf-json = "0.15.2"
gltf = "0.15.2"
plotters = "0.3.1"
pollster = "0.2.5"
wgpu = "0.12.0"
winit = "0.26.1"